### PR TITLE
ajax-ui

### PR DESCRIPTION
**Pull request by DzmitryKosmach**

### CODE REVIEW

**Review by NikitaSedyx — CHANGES_REQUESTED** [review]
wrong approach to have all layouts in dom and use hidden attribute to show/hide them

**Comment by DzmitryKosmach** [comment]
https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/7/commits/7f8ee6d0c52a09ddf45370d1c03c046ac9023464


2017-05-26 8:55 GMT+03:00 Mikita Siadykh <notifications@github.com>:

**Review by NikitaSedyx — COMMENTED** [review]
it's better, but you could create your dom structure with JS without find-update etc

**Comment by DzmitryKosmach** [comment]
https://github.com/DzmitryKosmach/DzmitryKosmach.github.io/pull/7/commits/6a9baa2653ec3f9ca0d018421105bf8bee775fd7


2017-06-03 16:41 GMT+03:00 Mikita Siadykh <notifications@github.com>:

**Pull request merged**
